export const categories = [
    {
      category: "Groceries",
      items: [
        {
          name: "Apple",
          price: 120,
          discountPrice: 100,
          offersPercentage: "16%",
          address: "Fresh Mart, New York",
        },
        {
          name: "Rice",
          price: 60,
          discountPrice: 50,
          offersPercentage: "17%",
          address: "Super Grocery, San Francisco",
        },
        {
          name: "Olive Oil",
          price: 500,
          discountPrice: 450,
          offersPercentage: "10%",
          address: "Grocery Hub, Chicago",
        },
        {
          name: "Apple",
          price: 120,
          discountPrice: 100,
          offersPercentage: "16%",
          address: "Fresh Mart, New York",
        },
        {
          name: "Rice",
          price: 60,
          discountPrice: 50,
          offersPercentage: "17%",
          address: "Super Grocery, San Francisco",
        },
        {
          name: "Olive Oil",
          price: 500,
          discountPrice: 450,
          offersPercentage: "10%",
          address: "Grocery Hub, Chicago",
        },
      ],
    },
    {
      category: "Electronics",
      items: [
        {
          name: "Smartphone",
          price: 25000,
          discountPrice: 22000,
          offersPercentage: "12%",
          address: "Tech World, Los Angeles",
        },
        {
          name: "Laptop",
          price: 70000,
          discountPrice: 65000,
          offersPercentage: "7%",
          address: "Electro Hub, Boston",
        },
        {
          name: "Headphones",
          price: 3000,
          discountPrice: 2700,
          offersPercentage: "10%",
          address: "Digital Plaza, Miami",
        },
        {
          name: "Smartphone",
          price: 25000,
          discountPrice: 22000,
          offersPercentage: "12%",
          address: "Tech World, Los Angeles",
        },
        {
          name: "Laptop",
          price: 70000,
          discountPrice: 65000,
          offersPercentage: "7%",
          address: "Electro Hub, Boston",
        },
        {
          name: "Headphones",
          price: 3000,
          discountPrice: 2700,
          offersPercentage: "10%",
          address: "Digital Plaza, Miami",
        },
      ],
    },
    {
      category: "Fashion",
      items: [
        {
          name: "T-shirt",
          price: 800,
          discountPrice: 700,
          offersPercentage: "12%",
          address: "Fashion Store, New York",
        },
        {
          name: "Jeans",
          price: 2000,
          discountPrice: 1800,
          offersPercentage: "10%",
          address: "Trend Spot, Dallas",
        },
        {
          name: "Jacket",
          price: 4000,
          discountPrice: 3500,
          offersPercentage: "13%",
          address: "Style Boutique, Chicago",
        },
        {
          name: "T-shirt",
          price: 800,
          discountPrice: 700,
          offersPercentage: "12%",
          address: "Fashion Store, New York",
        },
        {
          name: "Jeans",
          price: 2000,
          discountPrice: 1800,
          offersPercentage: "10%",
          address: "Trend Spot, Dallas",
        },
        {
          name: "Jacket",
          price: 4000,
          discountPrice: 3500,
          offersPercentage: "13%",
          address: "Style Boutique, Chicago",
        },
      ],
    },
    {
      category: "Footwear",
      items: [
        {
          name: "Sneakers",
          price: 3000,
          discountPrice: 2500,
          offersPercentage: "17%",
          address: "Shoe World, San Francisco",
        },
        {
          name: "Formal Shoes",
          price: 4000,
          discountPrice: 3500,
          offersPercentage: "12%",
          address: "Footwear Hub, Los Angeles",
        },
        {
          name: "Sandals",
          price: 1500,
          discountPrice: 1300,
          offersPercentage: "13%",
          address: "Shoe Plaza, Chicago",
        },
        {
          name: "Sneakers",
          price: 3000,
          discountPrice: 2500,
          offersPercentage: "17%",
          address: "Shoe World, San Francisco",
        },
        {
          name: "Formal Shoes",
          price: 4000,
          discountPrice: 3500,
          offersPercentage: "12%",
          address: "Footwear Hub, Los Angeles",
        },
        {
          name: "Sandals",
          price: 1500,
          discountPrice: 1300,
          offersPercentage: "13%",
          address: "Shoe Plaza, Chicago",
        },
      ],
    },
  ];

  export const allProducts=[
    {
        name: "Apple",
        price: 120,
        discountPrice: 100,
        offersPercentage: "16%",
        address: "Fresh Mart, New York",
      },
      {
        name: "Rice",
        price: 60,
        discountPrice: 50,
        offersPercentage: "17%",
        address: "Super Grocery, San Francisco",
      },
      {
        name: "Olive Oil",
        price: 500,
        discountPrice: 450,
        offersPercentage: "10%",
        address: "Grocery Hub, Chicago",
      },
      {
        name: "Sneakers",
        price: 3000,
        discountPrice: 2500,
        offersPercentage: "17%",
        address: "Shoe World, San Francisco",
      },
      {
        name: "Formal Shoes",
        price: 4000,
        discountPrice: 3500,
        offersPercentage: "12%",
        address: "Footwear Hub, Los Angeles",
      },
      {
        name: "Sandals",
        price: 1500,
        discountPrice: 1300,
        offersPercentage: "13%",
        address: "Shoe Plaza, Chicago",
      },
      {
        name: "Smartphone",
        price: 25000,
        discountPrice: 22000,
        offersPercentage: "12%",
        address: "Tech World, Los Angeles",
      },
      {
        name: "Laptop",
        price: 70000,
        discountPrice: 65000,
        offersPercentage: "7%",
        address: "Electro Hub, Boston",
      },
      {
        name: "Headphones",
        price: 3000,
        discountPrice: 2700,
        offersPercentage: "10%",
        address: "Digital Plaza, Miami",
      },
      {
        name: "Apple",
        price: 120,
        discountPrice: 100,
        offersPercentage: "16%",
        address: "Fresh Mart, New York",
      },
      {
        name: "Rice",
        price: 60,
        discountPrice: 50,
        offersPercentage: "17%",
        address: "Super Grocery, San Francisco",
      },
      {
        name: "Olive Oil",
        price: 500,
        discountPrice: 450,
        offersPercentage: "10%",
        address: "Grocery Hub, Chicago",
      },
      {
        name: "Sneakers",
        price: 3000,
        discountPrice: 2500,
        offersPercentage: "17%",
        address: "Shoe World, San Francisco",
      },
      {
        name: "Formal Shoes",
        price: 4000,
        discountPrice: 3500,
        offersPercentage: "12%",
        address: "Footwear Hub, Los Angeles",
      },
      {
        name: "Sandals",
        price: 1500,
        discountPrice: 1300,
        offersPercentage: "13%",
        address: "Shoe Plaza, Chicago",
      },
      {
        name: "Smartphone",
        price: 25000,
        discountPrice: 22000,
        offersPercentage: "12%",
        address: "Tech World, Los Angeles",
      },
      {
        name: "Laptop",
        price: 70000,
        discountPrice: 65000,
        offersPercentage: "7%",
        address: "Electro Hub, Boston",
      },
      {
        name: "Headphones",
        price: 3000,
        discountPrice: 2700,
        offersPercentage: "10%",
        address: "Digital Plaza, Miami",
      },
      {
        name: "Apple",
        price: 120,
        discountPrice: 100,
        offersPercentage: "16%",
        address: "Fresh Mart, New York",
      },
      {
        name: "Rice",
        price: 60,
        discountPrice: 50,
        offersPercentage: "17%",
        address: "Super Grocery, San Francisco",
      },
      {
        name: "Olive Oil",
        price: 500,
        discountPrice: 450,
        offersPercentage: "10%",
        address: "Grocery Hub, Chicago",
      },
      {
        name: "Sneakers",
        price: 3000,
        discountPrice: 2500,
        offersPercentage: "17%",
        address: "Shoe World, San Francisco",
      },
      {
        name: "Formal Shoes",
        price: 4000,
        discountPrice: 3500,
        offersPercentage: "12%",
        address: "Footwear Hub, Los Angeles",
      },
      {
        name: "Sandals",
        price: 1500,
        discountPrice: 1300,
        offersPercentage: "13%",
        address: "Shoe Plaza, Chicago",
      },
      {
        name: "Smartphone",
        price: 25000,
        discountPrice: 22000,
        offersPercentage: "12%",
        address: "Tech World, Los Angeles",
      },
      {
        name: "Laptop",
        price: 70000,
        discountPrice: 65000,
        offersPercentage: "7%",
        address: "Electro Hub, Boston",
      },
      {
        name: "Headphones",
        price: 3000,
        discountPrice: 2700,
        offersPercentage: "10%",
        address: "Digital Plaza, Miami",
      },
  ]